### ISSUE TITLE
Can an event be called when a page is refreshed through Refresh Button,F5 key or when the window is closed 

### ISSUE THREAD

**Issue by pardeshibhushan** [Microsoft/BotFramework-Samples#10]
Hi,

I have built a Chatbot using Microsoft Bot Framework and Node.js . 
I have an issue that i want to send chat logs when a web page is refreshed using refresh button,f5 key or when a window is closed.Is it possible to detect page refresh or call an event in node.js -botframework when a page is refreshed .

Thankyou.

**Comment by RobStand** [comment]
Please try this resource for help. https://docs.microsoft.com/en-us/bot-framework/resources-links-help
