### ISSUE TITLE
Issue with variable scope in StackoverflowBot

### ISSUE THREAD

**Issue by pmadusud** [Microsoft/BotFramework-Samples#11]
Hi, 
There seems to be an issue with the variable scope of the variables defined in each of the modules like qnaclient.js etc., The current code which defines the value as below doesn't seem to work.

const QNA_MAKER_URL = `${process.env.QNA_URL}/knowledgebases`;

function Client (opts) {
    if (!opts.knowledgeBaseId) throw new Error('knowledgeBaseId is required');
    if (!opts.subscriptionKey) throw new Error('subscriptionKey is required');

    this.knowledgeBaseId = opts.knowledgeBaseId;
    this.subscriptionKey = opts.subscriptionKey;
    this.scoreThreshold = opts.scoreThreshold ? opts.scoreThreshold : 20; // 20 is the default
}

Client.prototype.post = async (opts, cb) => {
    if (!opts.question) throw new Error('question is required');
    cb = cb || (() => { });
    const url = `${QNA_MAKER_URL}/${this.knowledgeBaseId}/generateAnswer`;

When the Post function is executed, the this object is empty and the this.knowledgeBaseId returns undefined. 

I had to change the code to the below to make this work.
const rp = require('request-promise');
const smallTalkReplies = require('./smalltalk');
const QNA_URL = process.env.QNA_URL;
const QNA_MAKER_URL = `${process.env.QNA_URL}/knowledgebases`;
var knowledgeBaseId;
var subscriptionKey;
var scoreThreshold;

function Client (opts) {
    if (!opts.knowledgeBaseId) throw new Error('knowledgeBaseId is required');
    if (!opts.subscriptionKey) throw new Error('subscriptionKey is required');

    knowledgeBaseId = opts.knowledgeBaseId;
    subscriptionKey = opts.subscriptionKey;
    scoreThreshold = opts.scoreThreshold ? opts.scoreThreshold : 20; // 20 is the default
}

Client.prototype.post = async (opts, cb) => {
    if (!opts.question) throw new Error('question is required');
    cb = cb || (() => { });

    const url = `${QNA_MAKER_URL}/${knowledgeBaseId}/generateAnswer`;

I am running Node 9.0.0 for your reference. I am not sure if I am missing something and why I am getting the issue described. It will be great to get some insights from you on this.

Thanks
--Madhu

**Comment by wingfeng** [comment]
I got the same problem when I run the script on Windows with Node.js 8.9.1 . But is seems that running in Linux is fine.
so I change the code like this.

`const rp = require('request-promise');

function BingSearchClient (opts) {
    if (!opts.bingSearchConfig) throw new Error('bingSearchConfig is required');
    if (!opts.bingSearchKey) throw new Error('bingSearchKey is required');

    this.bingSearchConfig = opts.bingSearchConfig;
    this.bingSearchKey = opts.bingSearchKey;
    this.bingSearchCount = 6;
    this.bingSearchMkt = "en-us";
    this.bingSearchBaseUrl = "https://api.cognitive.microsoft.com/bingcustomsearch/v5.0/search";
    this.bingSearchMaxSearchStringSize = 150;
	this.get = async (opts, cb) => {
    if (!opts.searchText) throw new Error('Search text is required');
    cb = cb || (() => {});

    const searchText = opts.searchText.substring(0, this.bingSearchMaxSearchStringSize).trim();

    const url = this.bingSearchBaseUrl + "?"
                + `q=${encodeURIComponent(searchText)}`
                + `&customconfig=${this.bingSearchConfig}`
                + `&count=${this.bingSearchCount}`
                + `&mkt=${this.bingSearchMkt}`
                + "&offset=0&responseFilter=Webpages&safesearch=Strict";

    const options = {
        method: 'GET',
        uri: url,
        json: true,
        headers: {
            "Ocp-Apim-Subscription-Key": this.bingSearchKey
        }
    };

    await rp(options)
        .then((body) => {
            // POST succeeded
            return cb(null, body);
        })
        .catch((err) => {
            // POST failed
            return cb(err);
        });
	}
}
module.exports = BingSearchClient;
`
embed get function to the first brace.

**Comment by Kaiqb** [comment]
We are no longer maintaining this repo for samples. The official bot builder samples repo is here: https://github.com/Microsoft/BotBuilder-Samples for V3 and V4.
