### ISSUE TITLE
Where shall I build and deploy the mock channel?

### ISSUE THREAD

**Issue by QiiLin** [Microsoft/BotFramework-Samples#20]
I am trying to do a load testing on my Bot, I follow the instruction on this blog https://blog.botframework.com/2017/06/19/load-testing-a-bot/, So I want to use the sample code here to try it out, however when I read about the  README.md, It states:
to use: 
    - build and deploy
But I don't know where shall I deploy to, I tried the azure web app....it does not work.
Can anyone give me a lead on where I can deploy this Mock Channel?

**Comment by Kaiqb** [comment]
This repo is no longer being maintained for samples. The official samples are here: https://github.com/Microsoft/BotBuilder-Samples for both V3 and V4.
