### ISSUE TITLE
Missing one of BOTBUILDER_APP_ID, BOTBUILDER_APP_PASSWORD

### ISSUE THREAD

**Issue by dps999** [Microsoft/BotFramework-Samples#3]
Hi,
Node 8.6

Dependencies installed.

Missing one of BOTBUILDER_APP_ID, BOTBUILDER_APP_PASSWORD,     LUIS_MODEL, KB_ID, QNA_KEY, QNA_URL, BING_SEARCH_CONFIG, BING_SEARCH_KEY,     TEXT_ANALYTICS_KEY, TEXT_ANALYTICS_URL, DIALOG_ANALYZER_CLIENTID, DIALOG_ANALYZER_KEY or DIALOG_ANALYZER_URL     in environment variables!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stackbot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stackbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by nrobert** [comment]
Hi,

Did you set all those settings? (see readme: https://github.com/Microsoft/BotFramework-Samples/tree/master/StackOverflow-Bot)

**Comment by dps999** [comment]
Thanks,
looks like it started successfully by run code --install-extension stocode-0.1.1.vsix
