### ISSUE TITLE
Missing one of BOTBUILDER_APP_ID, BOTBUILDER_APP_PASSWORD,     LUIS_MODEL, KB_ID, QNA_KEY, QNA_URL, BING_SEARCH_CONFIG, BING_SEARCH_KEY,     TEXT_ANALYTICS_KEY, TEXT_ANALYTICS_URL, DIALOG_ANALYZER_CLIENTID, DIALOG_ANALYZER_KEY or DIALOG_ANALYZER_URL     in environment variables!

### ISSUE THREAD

**Issue by quentinharris** [Microsoft/BotFramework-Samples#32]
I am following the instructions for installing stackoverflow bot. I am at the npm run start but keep getting:
Missing one of BOTBUILDER_APP_ID, BOTBUILDER_APP_PASSWORD,     LUIS_MODEL, KB_ID, QNA_KEY, QNA_URL, BING_SEARCH_CONFIG, BING_SEARCH_KEY,     TEXT_ANALYTICS_KEY, TEXT_ANALYTICS_URL, DIALOG_ANALYZER_CLIENTID, DIALOG_ANALYZER_KEY or DIALOG_ANALYZER_URL     in environment variables!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stackbot@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stackbot@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

How do I resolve this? Do I even need a key etc? The instructions seem to imply I should only need to run start and then Navigate to http://localhost:3978/ to start interacting with your bot.

Is this a known issue?

**Comment by Kaiqb** [comment]
Closing this issue as we are no longer maintaining the repo for samples. The official Bot Builder Samples repo is here: https://github.com/Microsoft/BotBuilder-Samples/ for both V3 and V4 bots.
