### ISSUE TITLE
Speech to Text is not working when web chat is embeded in ionic framework application

### ISSUE THREAD

**Issue by Kumar3010** [Microsoft/BotFramework-Samples#39]
I have enabled speech in my bot framework code. the speech service is working fine in browser Chrome and Edge but when i have embeded this in a web view in xamarin applicaton speech doesnt work.
i have tried doing it in ionic cross platform framework where i have embeded this as iframe. could you please look into that issue.

**Comment by Kumar3010** [comment]
HI Team,
any update on the isssue

**Comment by Kaiqb** [comment]
For support options, please refer to https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0.
