### ISSUE TITLE
Can't get token - 403

### ISSUE THREAD

**Issue by dps999** [Microsoft/BotFramework-Samples#4]
https://dev.botframework.com/bots/new 
opens with Error 403 - This web app is stopped.

**Comment by iampeterbanjo** [comment]
It seems to be working.

![screen shot 2017-09-29 at 12 22 34](https://user-images.githubusercontent.com/221853/31014050-ebb83816-a510-11e7-8084-64506eb428c4.png)

**Comment by dps999** [comment]
Thanks,
looks like problem was in my safari.
