### ISSUE TITLE
Links for ContosoCafe return 404

### ISSUE THREAD

**Issue by jjgriff93** [Microsoft/BotFramework-Samples#42]

**Comment by Kaiqb** [comment]
The ContosoCafe sample is here:
[C#] https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/csharp_dotnetcore/51.cafe-bot
[]Node] https://github.com/Microsoft/BotBuilder-Samples/tree/master/samples/javascript_nodejs/51.cafe-bot
