### ISSUE TITLE
in BotFramework V4, how to add LUIS app subscription key to the .bot file

### ISSUE THREAD

**Issue by Basavarajsk1992** [Microsoft/BotFramework-Samples#44]
For LUIS app i have generated new keys, those key how can i include in azure bot which is build on bot framework v4.
I tried to add subscriptionKey value to endpoint key in .bot file still, it is not working.
please help me on this.
Thank you.

**Comment by Kaiqb** [comment]
For support issues, please use [Stackoverflow ](https://stackoverflow.com/questions/tagged/botframework).
