### ISSUE TITLE
Why do we have 2 'Samples' repos?

### ISSUE THREAD

**Issue by brandonh-msft** [Microsoft/BotFramework-Samples#61]
It's confusing to users which Samples repo they should be looking at. Additionally our docs seem to reference some samples in this repo, and some samples in the **BotBuilder**-Samples repo; we should consolidate these.

I've filed a similar issue on the BotBuilder repo [here](https://github.com/Microsoft/BotBuilder-Samples/issues/1199).

**Comment by Kaiqb** [comment]
That's is the plan. We want to merge everything into botbuilder-samples repo.

**Comment by brandonh-msft** [comment]
@Kaiqb It may be worthwhile, then, to turn off the 'Issues' and 'Pull Requests' capabilities of this repo and say this at the very top of README.md, no? And leave this issue open until that work is complete?

cc @cmayomsft @ovishesh @sgellock
