### ISSUE TITLE
the demo link for "Speech Services with JS Demo" is broken.

### ISSUE THREAD

**Issue by Woolei** [microsoft/BotFramework-Samples#69]
it should be 
https://microsoft.github.io/BotFramework-WebChat/06.c.cognitive-services-speech-services-js

but not 
https://microsoft.github.io/BotFramework-WebChat/6.c.cognitive-services-speech-services-js

**Comment by MatthiasGwiozda** [comment]
For me the Links on this page are not broken:

[https://microsoft.github.io/BotFramework-WebChat/](https://microsoft.github.io/BotFramework-WebChat/)

**Comment by corinagum** [comment]
Woops, mis-read which repo this is in. I did a quick sample fix but that won't be necessary. Please see https://github.com/microsoft/BotBuilder-Samples for current updates. 

As @MatthiasGwiozda pointed out, https://microsoft.github.io/BotFramework-WebChat/ also contains a host of official samples that are kept up to date.
