### ISSUE TITLE
Help with QnA bot  for Q2A system

### ISSUE THREAD

**Issue by edzai** [microsoft/BotFramework-Samples#75]
Am wondering if you can guide me with the problem that I have. 
I have a Q2A (php) installation on https://mathsgee.com/qna which is a platform for students to ask and answer math questions. I would like to create a QnA bot that answers users' questions. I hope to deploy the bot on various platforms like social media and learning management systems. 
Since Q2A is a stackoverflow clone I thought you might be able to guide me, thanks.

**Comment by tsuwandy** [comment]
@edzai, Bot Framework Support teams prefers "how to" question posted on Stacks Overflow.
